### ISSUE TITLE
Scoped styles

### ISSUE THREAD

**Issue by nutgaard** [nutgaard/react-storybook-addon-sections#1]
Addon styling effects the examples. 
The use of `h2` etc in examples are subject to the styles added to the addons headers.

```css
.storybook-addons-info h1, 
.storybook-addons-info h2, 
.storybook-addons-info h3, 
.storybook-addons-info h4, 
.storybook-addons-info h5, 
.storybook-addons-info h6 {
  margin-top: 0;
}
```
